---
- name: "Task 2: Install Docker and Git on site1 hosts"
  hosts: site1
  become: yes
  gather_facts: yes
  
  vars:
    docker_users: "{{ hostvars[inventory_hostname].ansible_user }}"
  
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: ['packages']

    - name: Install required packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      tags: ['packages']

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: ['docker']

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      tags: ['docker']

    - name: Update package cache after adding Docker repo
      apt:
        update_cache: yes
      tags: ['docker']

    - name: Install Docker CE and related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
      tags: ['docker']

    - name: Install Git
      apt:
        name: git
        state: present
      tags: ['git']

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      tags: ['docker']

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      tags: ['docker']

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false
      tags: ['verify']

    - name: Verify Git installation
      command: git --version
      register: git_version
      changed_when: false
      tags: ['verify']

    - name: Display installation results
      debug:
        msg: |
          Docker version: {{ docker_version.stdout }}
          Git version: {{ git_version.stdout }}
          User {{ ansible_user }} added to docker group
      tags: ['verify']

    - name: Reboot to ensure group changes take effect
      reboot:
        msg: "Reboot initiated by Ansible for Docker group changes"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
      tags: ['reboot']

    - name: Wait for system to become reachable after reboot
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      tags: ['reboot']

    - name: Test Docker without sudo (after reboot)
      command: docker run hello-world
      become_user: "{{ ansible_user }}"
      register: docker_test
      tags: ['test']

    - name: Display Docker test result
      debug:
        var: docker_test.stdout_lines
      tags: ['test']
