---
- name: Perform dist-upgrade and reboot all hosts
  hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - ../vars/main.yml
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_update_result
      
    - name: Perform dist-upgrade
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      register: upgrade_result
      
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      
    - name: Reboot system if required
      reboot:
        msg: "Reboot initiated by Ansible for dist-upgrade"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when: reboot_required_file.stat.exists or upgrade_result.changed
      
    - name: Wait for system to become reachable
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when: reboot_required_file.stat.exists or upgrade_result.changed
      
    - name: Display upgrade summary
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          Upgrade performed: {{ upgrade_result.changed }}
          Reboot required: {{ reboot_required_file.stat.exists }}
