---
- name: "Task 4: Setup Netcat service on all hosts"
  hosts: all
  become: yes
  gather_facts: yes
  
  vars:
    netcat_port: 9090
    
  tasks:
    - name: Set netcat user and group based on ansible_user
      set_fact:
        netcat_user: "{{ ansible_user }}"
        netcat_group: "{{ ansible_user }}"

    - name: Install netcat package
      package:
        name: "{{ 'netcat-openbsd' if ansible_os_family == 'Debian' else 'nmap-ncat' }}"
        state: present
      tags: ['install']

    - name: Create systemd service file for netcat
      template:
        src: netcat.service.j2
        dest: "/etc/systemd/system/netcat-{{ netcat_port }}.service"
        owner: root
        group: root
        mode: '0644'
      vars:
        template_content: |
          [Unit]
          Description=Netcat listener on port {{ netcat_port }}
          After=network.target
          Wants=network.target

          [Service]
          Type=simple
          User={{ netcat_user }}
          Group={{ netcat_group }}
          ExecStart=/bin/nc -l -k -p {{ netcat_port }}
          Restart=always
          RestartSec=5
          StandardOutput=journal
          StandardError=journal

          # Security settings
          NoNewPrivileges=true
          PrivateTmp=true
          ProtectSystem=strict
          ProtectHome=true

          [Install]
          WantedBy=multi-user.target
      notify: 
        - reload systemd
        - restart netcat service
      tags: ['service']

    - name: Create netcat service file (alternative method)
      copy:
        content: |
          [Unit]
          Description=Netcat listener on port {{ netcat_port }}
          After=network.target
          Wants=network.target

          [Service]
          Type=simple
          User={{ netcat_user }}
          Group={{ netcat_group }}
          ExecStart=/bin/nc -l -k -p {{ netcat_port }}
          Restart=always
          RestartSec=5
          StandardOutput=journal
          StandardError=journal

          # Security settings
          NoNewPrivileges=true
          PrivateTmp=true
          ProtectSystem=strict
          ProtectHome=true

          [Install]
          WantedBy=multi-user.target
        dest: "/etc/systemd/system/netcat-{{ netcat_port }}.service"
        owner: root
        group: root
        mode: '0644'
      tags: ['service']

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
      tags: ['service']

    - name: Start and enable netcat service
      systemd:
        name: "netcat-{{ netcat_port }}"
        state: started
        enabled: yes
      tags: ['service']

    - name: Check if service is running
      systemd:
        name: "netcat-{{ netcat_port }}"
      register: netcat_service_status
      tags: ['verify']

    - name: Display service status
      debug:
        msg: |
          Service: netcat-{{ netcat_port }}
          Status: {{ netcat_service_status.status.ActiveState }}
          Enabled: {{ netcat_service_status.status.UnitFileState }}
      tags: ['verify']

    - name: Test netcat service connectivity
      wait_for:
        port: "{{ netcat_port }}"
        host: "{{ ansible_default_ipv4.address }}"
        timeout: 10
      tags: ['test']

    - name: Display connection test results
      debug:
        msg: "✅ Netcat service is listening on {{ ansible_default_ipv4.address }}:{{ netcat_port }}"
      tags: ['test']

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart netcat service
      systemd:
        name: "netcat-{{ netcat_port }}"
        state: restarted
